### ISSUE TITLE
Passwordreset not working

### ISSUE THREAD

**Issue by Docmale** [digitalfabrik/integreat-compass#131]
### Describe the Bug
When requesting a password reset, no email arrives for "martin.lehmann+compass-provider@tuerantuer.org"

**Comment by JoeyStk** [comment]
@svenseeberg Since we assume this to be an issue with the server configuration, could you please have a look at it? :blush:

**Comment by svenseeberg** [comment]
E-mail definitely was not yet configured. But I think there is something else going on. I still get an 500 error, but the log is empty. When I enable the Debug mode, it obviously works ;-)

**Comment by svenseeberg** [comment]
```
Sep 13 14:12:50 ERROR   django.request - 500 Internal Server Error: /accounts/reset-password/
Traceback (most recent call last):
  File "/opt/integreat-compass/.venv/lib/python3.9/site-packages/django/core/handlers/exception.py", line 55, in inner
    response = get_response(request)
  File "/opt/integreat-compass/.venv/lib/python3.9/site-packages/django/core/handlers/base.py", line 197, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "/opt/integreat-compass/.venv/lib/python3.9/site-packages/django/views/generic/base.py", line 104, in view
    return self.dispatch(request, *args, **kwargs)
  File "/opt/integreat-compass/.venv/lib/python3.9/site-packages/django/views/generic/base.py", line 143, in dispatch
    return handler(request, *args, **kwargs)
  File "/opt/integreat-compass/.venv/lib/python3.9/site-packages/django/views/generic/edit.py", line 153, in post
    return self.form_valid(form)
  File "/opt/integreat-compass/.venv/lib/python3.9/site-packages/integreat_compass/cms/views/authentication/password_reset_request_view.py", line 43, in form_valid
    send_reset_mail(user)
  File "/opt/integreat-compass/.venv/lib/python3.9/site-packages/integreat_compass/cms/utils/email_utils.py", line 105, in send_reset_mail
    send_mail(
  File "/opt/integreat-compass/.venv/lib/python3.9/site-packages/integreat_compass/cms/utils/email_utils.py", line 54, in send_mail
    email.send()
  File "/opt/integreat-compass/.venv/lib/python3.9/site-packages/django/core/mail/message.py", line 298, in send
    return self.get_connection(fail_silently).send_messages([self])
  File "/opt/integreat-compass/.venv/lib/python3.9/site-packages/django/core/mail/backends/smtp.py", line 127, in send_messages
    new_conn_created = self.open()
  File "/opt/integreat-compass/.venv/lib/python3.9/site-packages/django/core/mail/backends/smtp.py", line 85, in open
    self.connection = self.connection_class(
  File "/usr/lib/python3.9/smtplib.py", line 253, in __init__
    (code, msg) = self.connect(host, port)
  File "/usr/lib/python3.9/smtplib.py", line 339, in connect
    self.sock = self._get_socket(host, port, self.timeout)
  File "/usr/lib/python3.9/smtplib.py", line 310, in _get_socket
    return socket.create_connection((host, port), timeout,
  File "/usr/lib/python3.9/socket.py", line 822, in create_connection
    for res in getaddrinfo(host, port, 0, SOCK_STREAM):
  File "/usr/lib/python3.9/socket.py", line 953, in getaddrinfo
    for res in _socket.getaddrinfo(host, port, family, type, proto, flags):
socket.gaierror: [Errno -2] Name or service not known
```
